### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by bermonch** [dogtopus/FT-Controller-FW#16]
Hi, i am an arcade stick builders.i can help you with the project.my email is doblado007@gmail.com. i would like to Talk with you.thanks regards

**Comment by dogtopus** [comment]
That's great. Are you interested in manufacturing and distributing the controller?

**Comment by kuwoh** [comment]
pretty sure you should email him mate

**Comment by bermonch** [comment]
> That's great. Are you interested in manufacturing and distributing the controller?

Hi,not exactly,only helping you if you need.i have laser cutting and knowledge on wiring,padhacking ,controla and programming.
I want to do an special control for dragons crown game.i think i can help you in the procces.
About teensy board,is compatible 2.0 or 3.2?

**Comment by dogtopus** [comment]
> About teensy board,is compatible 2.0 or 3.2?

It's only compatible with Teensy 3.x/LC at this moment. I plan to add support for other targets (mainly STM32 probably through tinyusb). As for AVR-based platforms, I was having the plan to support it but at this point I think it's not really worth investing extra time specifically for AVRs because ARM-based microcontrollers are getting more common and cheaper.

**Comment by bermonch** [comment]
> > About teensy board,is compatible 2.0 or 3.2?
> 
> It's only compatible with Teensy 3.x/LC at this moment. I plan to add support for other targets (mainly STM32 probably through tinyusb). As for AVR-based platforms, I was having the plan to support it but at this point I think it's not really worth investing extra time specifically for AVRs because ARM-based microcontrollers are getting more common and cheaper.

Ok.have you got Facebook,discord for talking?.please send me your account to doblado007@gmail.com. thanks

**Comment by dogtopus** [comment]
OK I sent you a message.
